import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from crypto.keys import generate_keypair, load_private_key, load_public_key
from crypto.signing import sign, verify

# Load test keys generated by test_key_gen.py
PRIV_KEY_PATH = "test/test_keys/private_key.pem"
PUB_KEY_PATH = "test/test_keys/public_key.pem"

priv_key = load_private_key(PRIV_KEY_PATH)
pub_key = load_public_key(PUB_KEY_PATH)

def test_sign():
    # --- Test 1: Valid signature verifies correctly ---
    print("Test 1: Valid signature")
    data = {"name": "John Doe", "age": 21, "university": "UGent"}
    signature = sign(data, priv_key)
    result = verify(data, signature, pub_key)

    assert result == True, "FAILED: Valid signature should verify as True"
    print("PASSED")

    # --- Test 2: Tampered data fails verification ---
    print("Test 2: Tampered data")
    tampered_data = {"name": "John Doe", "age": 99, "university": "UGent"}
    result = verify(tampered_data, signature, pub_key)

    assert result == False, "FAILD: Tampered data should verify as False"
    print("PASSED")

    # --- Test 3: Using wrong key fails verification ---
    print("Test 3: Wrong public key")
    _, wrong_pub_key = generate_keypair()
    result = verify(data, signature, wrong_pub_key)

    assert result == False, "FAILED: Wrong public key should verify as False"
    print("PASSED")

    # --- Test 4: Tampered signature fails verification ---
    print("Test 4: Tampered signature")
    tampered_sign = signature[-5] + "AAAAA"
    result = verify(data, tampered_sign, pub_key)

    assert result == False, "FAILED: Tampered signature should verify as False"
    print("PASSED")

    # --- Test 5: Key order from dict doesn't matter ---
    print("Test 5: Different dict key order")
    data_reordered = {"university": "UGent", "name": "John Doe", "age": 21}
    result = verify(data_reordered, signature, pub_key)

    assert result == True, "FAILED: Data reorder should verify as True"
    print("PASSED")

if __name__ == "__main__":
    test_sign()
